import Head from 'next/head'
import Calendar from '../components/Calendar/Calendar'
import Objectives from '../components/Objectives/Objectives'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Objectives/>
        <Calendar/>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
